window.MASOTTO_DB = {
  "property_master": [
    {
      "property_id": "MASOTTO4",
      "name": "Masotto Terrace View",
      "address": "Via Privata Umberto Masotto 4, 20133 Milano",
      "owner": "Armati Riccardo",
      "purchase_date": "2023-04-17",
      "purchase_price_eur": 230000,
      "pod_luce": "IT012E00186429",
      "fornitura_luce": "6045433825",
      "pdr_gas": "05260200407342",
      "cir": "015146-LNI-09408",
      "ape_class": "E",
      "ape_epgl_nren_kwh_m2": 132.76,
      "internet_ssid": "FASTWEB-FC918B",
      "fornitura_gas": "6045405179",
      "insurance_policy": "460438632",
      "insurance_expiry": "2027-03-02",
      "insurance_premium_eur": 1716,
      "internet_codice_cliente": "0289690826",
      "internet_monthly_cost_eur": 27.95,
      "activity_start_date": "2025-08-25"
    }
  ],
  "assets_mobile": [
    {
      "id": "EQ031",
      "tipo": "Frigorifero",
      "marca": "IKEA",
      "modello": "HUTTRA",
      "sn": "IK-FR-8890",
      "acquisto": "2023-10-02",
      "prezzo_eur": 409,
      "garanzia": "attiva (2028)"
    },
    {
      "id": "EQ032",
      "tipo": "Lavastoviglie",
      "marca": "IKEA",
      "modello": "MEDELSTOR",
      "sn": "IK-DW-221",
      "acquisto": "2023-10-02",
      "prezzo_eur": 419,
      "garanzia": "attiva (2028)"
    },
    {
      "id": "EQ033",
      "tipo": "Piano Cottura",
      "marca": "IKEA",
      "modello": "VILSTA",
      "sn": "IK-IND-55",
      "acquisto": "2023-10-02",
      "prezzo_eur": 239,
      "garanzia": "attiva (2028)"
    },
    {
      "id": "EQ034",
      "tipo": "Cappa",
      "marca": "IKEA",
      "modello": "UTDRAG",
      "sn": "-",
      "acquisto": "2023-10-02",
      "prezzo_eur": 149,
      "garanzia": "scaduta (2025)"
    },
    {
      "id": "EQ041",
      "tipo": "Lavasciuga",
      "marca": "MIELE",
      "modello": "WT 2670",
      "sn": "86308219",
      "acquisto": "2019-09-01",
      "prezzo_eur": 459,
      "garanzia": "scaduta (2021)"
    },
    {
      "id": "EQ037",
      "tipo": "TV 43",
      "marca": "HISENSE",
      "modello": "43E63KT",
      "sn": "36FG5G23113",
      "acquisto": "2023-11-06",
      "prezzo_eur": 299,
      "garanzia": "attiva (2027)"
    },
    {
      "id": "EQ093",
      "tipo": "Macchina Caffè",
      "marca": "LAVAZZA",
      "modello": "Jolie Evo",
      "sn": "YWU9AJPKFPKER9WC",
      "acquisto": "2024-11-14",
      "prezzo_eur": 94.9,
      "garanzia": "attiva (2026)"
    },
    {
      "id": "EQ044",
      "tipo": "Aspirapolvere 2in1",
      "marca": "BLACK+DECKER",
      "modello": "BXVMS600E",
      "sn": "44491HK",
      "acquisto": "2026-01-04",
      "prezzo_eur": 49,
      "garanzia": "attiva (2028)"
    },
    {
      "id": "EQ101",
      "tipo": "Asse/Stiro",
      "marca": "STANDARD",
      "modello": "Stiro Kit",
      "sn": "-",
      "acquisto": "2026-02-09",
      "prezzo_eur": 39,
      "garanzia": "n/a"
    },
    {
      "id": "EQ102",
      "tipo": "Frullatore",
      "marca": "STANDARD",
      "modello": "Blender",
      "sn": "-",
      "acquisto": "2026-02-09",
      "prezzo_eur": 59,
      "garanzia": "n/a"
    },
    {
      "id": "EQ103",
      "tipo": "Grucce",
      "marca": "GENERICO",
      "modello": "Set 10",
      "sn": "-",
      "acquisto": "2026-02-09",
      "prezzo_eur": 12,
      "garanzia": "n/a"
    }
  ],
  "supply_presets": [
    {
      "id": "SUP001",
      "nome": "Sapone Mani Liquido (Ricarica 1L)",
      "categoria": "Housekeeping",
      "quantita_standard": 2,
      "prezzo_stimato_eur": 3.5,
      "fornitura_consigliato": "Esselunga",
      "note": "Per i dosatori in bagno e cucina"
    },
    {
      "id": "SUP002",
      "nome": "Pastiglie Lavastoviglie (Sacco XL)",
      "categoria": "Housekeeping",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 12.9,
      "fornitura_consigliato": "Amazon",
      "note": "Verificare scorta ogni fine mese"
    },
    {
      "id": "SUP003",
      "nome": "Detersivo Lavatrice Liquido (Classico)",
      "categoria": "Housekeeping",
      "quantita_standard": 2,
      "prezzo_stimato_eur": 4.99,
      "fornitura_consigliato": "Esselunga",
      "note": "Essenziale per i lavaggi lenzuola/asciugamani in loco"
    },
    {
      "id": "SUP004",
      "nome": "Detergente Pavimenti Professionale",
      "categoria": "Housekeeping",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 5.5,
      "fornitura_consigliato": "Tigotà",
      "note": "Profumazione neutra/fresca"
    },
    {
      "id": "SUP005",
      "nome": "Sgrassatore Universale (Spray + Ricarica)",
      "categoria": "Housekeeping",
      "quantita_standard": 2,
      "prezzo_stimato_eur": 2.8,
      "fornitura_consigliato": "Esselunga",
      "note": "Per pulizia cucina e superfici dure"
    },
    {
      "id": "SUP006",
      "nome": "Gel Disincrostante WC",
      "categoria": "Housekeeping",
      "quantita_standard": 2,
      "prezzo_stimato_eur": 1.9,
      "fornitura_consigliato": "Tigotà",
      "note": "Presidio per igienizzazione bagno"
    },
    {
      "id": "SUP007",
      "nome": "Batterie AA/AAA (Multipack)",
      "categoria": "Housekeeping",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 8.5,
      "fornitura_consigliato": "Amazon",
      "note": "Per telecomandi TV, termostato clima e dispositivi vari"
    },
    {
      "id": "SUP008",
      "nome": "Spugne e Panni in Microfibra (Set multiuso)",
      "categoria": "Housekeeping",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 6.9,
      "fornitura_consigliato": "Esselunga",
      "note": "Ricambio ciclico necessario per garantire l'igiene"
    },
    {
      "id": "SUP009",
      "nome": "Set Asciugamani Bagno (Ricambio usura)",
      "categoria": "Biancheria",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 24.9,
      "fornitura_consigliato": "Amazon",
      "note": "Costo ciclico per sostituzione capi macchiati o logori"
    },
    {
      "id": "SUP010",
      "nome": "Set Lenzuola Matrimoniali (Ricambio usura)",
      "categoria": "Biancheria",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 34.9,
      "fornitura_consigliato": "IKEA",
      "note": "Costo ciclico per sostituzione capi macchiati o logori"
    },
    {
      "id": "SUP011",
      "nome": "Cialde Caffè (Box 100 pz)",
      "categoria": "Housekeeping",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 22,
      "fornitura_consigliato": "Amazon",
      "note": "Compatibili con la macchina Lavazza Jolie Evo dell'appartamento"
    },
    {
      "id": "SUP012",
      "nome": "Zucchero in bustine (Conf. 200 pz)",
      "categoria": "Housekeeping",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 4.5,
      "fornitura_consigliato": "Esselunga",
      "note": "Welcome kit di cortesia per la cucina"
    },
    {
      "id": "SUP013",
      "nome": "Tè in filtri (Scatola assortita 40 filtri)",
      "categoria": "Housekeeping",
      "quantita_standard": 1,
      "prezzo_stimato_eur": 3.9,
      "fornitura_consigliato": "Esselunga",
      "note": "Welcome kit di cortesia per la cucina"
    }
  ],
  "finances": [
    {
      "id": "UTL-0114",
      "date": "2023-05-31",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 91,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0115",
      "date": "2023-07-31",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 51,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0116",
      "date": "2023-09-30",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 50,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0117",
      "date": "2023-11-30",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 52,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0118",
      "date": "2024-01-31",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 53,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0119",
      "date": "2024-03-31",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 85,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0120",
      "date": "2024-05-31",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 100,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 1,
      "date": "2024-06-30",
      "description": "Condominio: Ordinaria 24/25 - Rata fp n. 1",
      "category": "Ordinaria",
      "amount_eur": 256.2,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0121",
      "date": "2024-07-31",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 184,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0122",
      "date": "2024-09-30",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 141,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 2,
      "date": "2024-11-15",
      "description": "Condominio: Ordinaria 24/25 - f.p. n. 2",
      "category": "Ordinaria",
      "amount_eur": 256.2,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0123",
      "date": "2024-11-30",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 157,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 21,
      "date": "2025-01-31",
      "description": "Canone RAI 2025",
      "category": "Tasse",
      "amount_eur": 203.7,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 3,
      "date": "2025-02-15",
      "description": "Condominio: Ordinaria 24/25 - Rata n. 3 e saldo",
      "category": "Ordinaria",
      "amount_eur": 522.16,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0005",
      "date": "2025-02-17",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 192,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0001",
      "date": "2025-03-17",
      "description": "utilities gas",
      "category": "Utenze",
      "amount_eur": 53,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 5,
      "date": "2025-03-20",
      "description": "Condominio: Rimozione MCA (Amianto) R1",
      "category": "Straordinaria",
      "amount_eur": 285.33,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 4,
      "date": "2025-04-01",
      "description": "Condominio: Ordinaria 24/25 - Rata n. 4",
      "category": "Ordinaria",
      "amount_eur": 395.77,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0006",
      "date": "2025-04-15",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 94,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 6,
      "date": "2025-06-15",
      "description": "Condominio: Rimozione MCA (Amianto) R2",
      "category": "Straordinaria",
      "amount_eur": 285.33,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 7,
      "date": "2025-06-15",
      "description": "Condominio: Ordinaria 25/26 - Rata fp n. 1",
      "category": "Ordinaria",
      "amount_eur": 305,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 22,
      "date": "2025-06-16",
      "description": "IMU Acconto 2025",
      "category": "Tasse",
      "amount_eur": 334,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0007",
      "date": "2025-06-16",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 89,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0002",
      "date": "2025-06-17",
      "description": "utilities gas",
      "category": "Utenze",
      "amount_eur": 54,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0008",
      "date": "2025-08-14",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 195,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 8,
      "date": "2025-09-01",
      "description": "Condominio: Ordinaria 25/26 - Rata fp n. 2",
      "category": "Ordinaria",
      "amount_eur": 305,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0003",
      "date": "2025-09-12",
      "description": "utilities gas",
      "category": "Utenze",
      "amount_eur": 68,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "MNT-0019",
      "date": "2025-10-12",
      "description": "Silicone lavandino",
      "category": "Manutenzione",
      "amount_eur": 57,
      "status": "completato",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0009",
      "date": "2025-10-13",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 103,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "MNT-0010",
      "date": "2025-10-16",
      "description": "Tinteggiatura bagno e parete soggiorno/cucina",
      "category": "Manutenzione",
      "amount_eur": 0,
      "status": "unificato/archiviato",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "MNT-0011",
      "date": "2025-10-16",
      "description": "TINTEGGIATURA BAGNO",
      "category": "Manutenzione",
      "amount_eur": 0,
      "status": "unificato/archiviato",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "MNT-0020",
      "date": "2025-10-16",
      "description": "Ripristino cassone tapparella",
      "category": "Manutenzione",
      "amount_eur": 40,
      "status": "completato",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "MNT-0021",
      "date": "2025-10-16",
      "description": "Tinteggiatura bagno, cucina e soggiorno",
      "category": "Manutenzione",
      "amount_eur": 283,
      "status": "completato",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "MNT-0022",
      "date": "2025-10-21",
      "description": "Siliconatura cornici finestre sale e tinteggiatura",
      "category": "Manutenzione",
      "amount_eur": 100,
      "status": "completato",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 24,
      "date": "2025-12-05",
      "description": "TARI 2025",
      "category": "Tasse",
      "amount_eur": 139,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 9,
      "date": "2025-12-15",
      "description": "Condominio: Ordinaria 25/26 - Rata n. 3 e saldo (Versato)",
      "category": "Ordinaria",
      "amount_eur": 543.42,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 10,
      "date": "2025-12-15",
      "description": "Condominio: Ordinaria 25/26 - Rata n. 3 (Residuo aperto)",
      "category": "Ordinaria",
      "amount_eur": 6.99,
      "status": "pending",
      "type": "expense"
    },
    {
      "id": 12,
      "date": "2025-12-15",
      "description": "Condominio: Terrazza 25/26 - Acconto lavori",
      "category": "Straordinaria",
      "amount_eur": 48.26,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 23,
      "date": "2025-12-16",
      "description": "IMU Saldo 2025",
      "category": "Tasse",
      "amount_eur": 334,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0004",
      "date": "2025-12-16",
      "description": "utilities gas",
      "category": "Utenze",
      "amount_eur": 87,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": "UTL-0010",
      "date": "2025-12-16",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 137,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 17,
      "date": "2026-01-04",
      "description": "Acquisto Asset: Aspirapolvere BLACK+DECKER",
      "category": "Asset",
      "amount_eur": 49,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 13,
      "date": "2026-01-15",
      "description": "Condominio: Terrazza 25/26 - Inizio lavori",
      "category": "Straordinaria",
      "amount_eur": 72.38,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 18,
      "date": "2026-02-09",
      "description": "Acquisto Asset: Asse Vileda / Frullatore / Grucce",
      "category": "Asset",
      "amount_eur": 110,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0011",
      "date": "2026-02-12",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 165,
      "status": "domiciliata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 11,
      "date": "2026-02-15",
      "description": "Condominio: Ordinaria 25/26 - Rata n. 4",
      "category": "Ordinaria",
      "amount_eur": 318.2,
      "status": "pending",
      "type": "expense"
    },
    {
      "id": 14,
      "date": "2026-02-15",
      "description": "Condominio: Terrazza 25/26 - SAL",
      "category": "Straordinaria",
      "amount_eur": 72.38,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 15,
      "date": "2026-03-15",
      "description": "Condominio: Terrazza 25/26 - Fine lavori",
      "category": "Straordinaria",
      "amount_eur": 48.26,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": 20,
      "date": "2026-04-07",
      "description": "A2A Gas (Dic 25-Feb 26)",
      "category": "Utenze",
      "amount_eur": 83,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0049",
      "date": "2026-04-07",
      "description": "utilities gas",
      "category": "Utenze",
      "amount_eur": 83,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 19,
      "date": "2026-05-05",
      "description": "A2A Luce (Feb-Mar 26)",
      "category": "Utenze",
      "amount_eur": 221,
      "status": "paid",
      "type": "expense"
    },
    {
      "id": "UTL-0048",
      "date": "2026-05-05",
      "description": "utilities electricity",
      "category": "Utenze",
      "amount_eur": 221,
      "status": "pagata",
      "type": "expense",
      "source": "2mdb_current_v43"
    },
    {
      "id": 16,
      "date": "2026-05-31",
      "description": "Condominio: Ordinaria 26/27 - Rata fp n. 1",
      "category": "Ordinaria",
      "amount_eur": 329.89,
      "status": "pending",
      "type": "expense"
    }
  ],
  "bookings": [
    {
      "id": 108603411,
      "guest": "Gabriela Stempka",
      "check_in": "2025-08-25",
      "nights": 2,
      "pax": 1,
      "source": "Airbnb",
      "gross_eur": 143,
      "commission_eur": 0,
      "city_tax_eur": 0,
      "cleaning_eur": 45
    },
    {
      "id": 108845191,
      "guest": "Flavio Nakakura",
      "check_in": "2025-08-27",
      "nights": 7,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 452,
      "commission_eur": 0,
      "city_tax_eur": 44.1,
      "cleaning_eur": 45
    },
    {
      "id": 107696481,
      "guest": "Christie Swainston",
      "check_in": "2025-09-04",
      "nights": 3,
      "pax": 1,
      "source": "Airbnb",
      "gross_eur": 441,
      "commission_eur": 0,
      "city_tax_eur": 0,
      "cleaning_eur": 45
    },
    {
      "id": 109488256,
      "guest": "Flavio Nakakura",
      "check_in": "2025-09-07",
      "nights": 22,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 1267,
      "commission_eur": 0,
      "city_tax_eur": 88.2,
      "cleaning_eur": 80
    },
    {
      "id": 112211526,
      "guest": "Edwin Agallanes",
      "check_in": "2025-09-30",
      "nights": 13,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 900,
      "commission_eur": 0,
      "city_tax_eur": 81.3,
      "cleaning_eur": 45
    },
    {
      "id": 113874751,
      "guest": "Maja Janevska",
      "check_in": "2025-10-16",
      "nights": 10,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 826,
      "commission_eur": 0,
      "city_tax_eur": 63,
      "cleaning_eur": 45
    },
    {
      "id": 115489991,
      "guest": "Irilla Santana Nobre Goncalves",
      "check_in": "2025-10-26",
      "nights": 21,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 1226,
      "commission_eur": 0,
      "city_tax_eur": 88.2,
      "cleaning_eur": 80
    },
    {
      "id": 115489992,
      "guest": "Irilla Santana Nobre Goncalves",
      "check_in": "2025-11-16",
      "nights": 14,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 700,
      "commission_eur": 0,
      "city_tax_eur": 88.2,
      "cleaning_eur": 45
    },
    {
      "id": 119791626,
      "guest": "Sara Dario",
      "check_in": "2025-12-04",
      "nights": 17,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 1026,
      "commission_eur": 0,
      "city_tax_eur": 88.2,
      "cleaning_eur": 80
    },
    {
      "id": 123607671,
      "guest": "Sara Dario",
      "check_in": "2026-01-12",
      "nights": 14,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 1428,
      "commission_eur": 0,
      "city_tax_eur": 133,
      "cleaning_eur": 45
    },
    {
      "id": 125904941,
      "guest": "Jessika de Miranda",
      "check_in": "2026-02-09",
      "nights": 21,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 1320.0,
      "commission_eur": 0.0,
      "city_tax_eur": 133.0,
      "cleaning_eur": 80.0,
      "taxable_gross_eur": 1320.0,
      "cedolare_base_eur": 1320.0,
      "receipt_total_display_eur": 1320.0,
      "gross_collected_eur": 1453.0,
      "city_tax_accounting": "partita_di_giro",
      "receipt_note": "Lordo/base cedolare 1320 già comprensivo di pulizie; city tax 133 separata. Contabilità Wise: entrata 1320 e due uscite a Riccardo da 550.",
      "check_out": "2026-03-02",
      "cedolare_21_eur": 277.2,
      "wise_movement_eur": 1320.0,
      "riccardo_direct_eur": 0.0,
      "payment_split": {
        "wise_eur": 1320.0,
        "riccardo_reimbursement_eur": 1100.0,
        "city_tax_eur": 133.0
      },
      "room_amount_eur": 1240.0,
      "cleaning_fee_eur": 80.0,
      "riccardo_reimbursement_eur": 1100.0,
      "riccardo_reimbursements": [
        {
          "date": "2026-02-09",
          "amount_eur": 550.0,
          "description": "Giroconto a Riccardo - Jessika tranche 1/2"
        },
        {
          "date": "2026-03-02",
          "amount_eur": 550.0,
          "description": "Giroconto a Riccardo - Jessika tranche 2/2"
        }
      ]
    },
    {
      "id": 214603781,
      "guest": "Elena Ratti",
      "check_in": "2026-03-13",
      "nights": 9,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 720,
      "commission_eur": 0,
      "city_tax_eur": 85.5,
      "cleaning_eur": 45
    },
    {
      "id": 214603782,
      "guest": "Marco Bellini",
      "check_in": "2026-03-26",
      "nights": 7,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 560,
      "commission_eur": 0,
      "city_tax_eur": 66.5,
      "cleaning_eur": 45
    },
    {
      "id": 214603783,
      "guest": "Giulia Conti",
      "check_in": "2026-04-06",
      "nights": 9,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 711,
      "commission_eur": 0,
      "city_tax_eur": 85.5,
      "cleaning_eur": 45
    },
    {
      "id": 214603784,
      "guest": "Luca Ferri",
      "check_in": "2026-04-20",
      "nights": 10,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 700,
      "commission_eur": 0,
      "city_tax_eur": 95,
      "cleaning_eur": 45
    },
    {
      "id": 214603785,
      "guest": "Florencia Anabel Luduena Godoy",
      "check_in": "2026-05-18",
      "nights": 30,
      "pax": 1,
      "source": "Diretta",
      "gross_eur": 2060,
      "commission_eur": 0,
      "city_tax_eur": 133,
      "cleaning_eur": 80
    }
  ],
  "tickets": [
    {
      "id": 2510121,
      "asset": "STR-009",
      "title": "Silicone lavandino",
      "status": "DONE",
      "date": "2025-10-12",
      "costo_lavoro": 40,
      "costo_materiali": 17,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 57,
      "payment_account": "Wise",
      "category": "Manutenzione"
    },
    {
      "id": 2510161,
      "asset": "STR-004",
      "title": "Ripristino cassone tapparella",
      "status": "DONE",
      "date": "2025-10-16",
      "costo_lavoro": 40,
      "costo_materiali": 0,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 40,
      "payment_account": "Wise",
      "category": "Manutenzione"
    },
    {
      "id": 2510122,
      "asset": "STR-001",
      "title": "Tinteggiatura bagno + cucina/soggiorno",
      "status": "DONE",
      "date": "2025-10-12",
      "costo_lavoro": 250,
      "costo_materiali": 133,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 383,
      "payment_account": "Wise",
      "category": "Manutenzione"
    },
    {
      "id": 2510211,
      "asset": "STR-004",
      "title": "Siliconatura cornici finestre sale e tinteggiatura",
      "status": "DONE",
      "date": "2025-10-21",
      "costo_lavoro": 100,
      "costo_materiali": 28,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 128,
      "payment_account": "Wise",
      "category": "Manutenzione"
    }
  ],
  "structural_assets": [
    {
      "id": "STR-001",
      "categoria": "Involucro",
      "nome": "Pareti Interne",
      "descrizione": "Intonaci e tinteggiatura smalto",
      "stato_check": "Ripristino Ott 2025",
      "life_years": 5
    },
    {
      "id": "STR-002",
      "categoria": "Involucro",
      "nome": "Soffitti",
      "descrizione": "Finitura muraria e pitturazioni",
      "stato_check": "Monitoraggio crepe",
      "life_years": 8
    },
    {
      "id": "STR-003",
      "categoria": "Involucro",
      "nome": "Pavimenti",
      "descrizione": "Gres Porcellanato e zoccolini",
      "stato_check": "Verifica fughe",
      "life_years": 15
    },
    {
      "id": "STR-004",
      "categoria": "Infissi",
      "nome": "Infissi Esterni",
      "descrizione": "PVC Doppio Vetro / Guarnizioni",
      "stato_check": "Check isolamento",
      "life_years": 30
    },
    {
      "id": "STR-005",
      "categoria": "Infissi",
      "nome": "Porte Interne",
      "descrizione": "Ante, telai e serrature",
      "stato_check": "Lubrificazione cerniere",
      "life_years": 20
    },
    {
      "id": "STR-006",
      "categoria": "Sicurezza",
      "nome": "Porta Ingresso",
      "descrizione": "Blindata Dierre / Cilindro Euro",
      "stato_check": "Check spioncino",
      "life_years": 40
    },
    {
      "id": "STR-007",
      "categoria": "Impianti",
      "nome": "Imp. Elettrico",
      "descrizione": "Quadro RCD, prese e frutti",
      "stato_check": "Certificato Ott 2023",
      "life_years": 20
    },
    {
      "id": "STR-008",
      "categoria": "Impianti",
      "nome": "Imp. Idraulico",
      "descrizione": "Tubazioni e attacchi cucina",
      "stato_check": "Audit scarichi OK",
      "life_years": 25
    },
    {
      "id": "STR-009",
      "categoria": "Bagno",
      "nome": "Comp. Fissi",
      "descrizione": "WC, lavabo e piatto doccia",
      "stato_check": "Verifica miscelatori",
      "life_years": 15
    },
    {
      "id": "STR-010",
      "categoria": "Sigilli",
      "nome": "Siliconature",
      "descrizione": "Sigillature bagno e cucina",
      "stato_check": "RIUSO: Silicone disp.",
      "life_years": 2
    },
    {
      "id": "STR-011",
      "categoria": "Clima",
      "nome": "Riscaldamento",
      "descrizione": "Centralizzato Techem / Valvole",
      "stato_check": "Contabilizzato Feb 26",
      "life_years": 20
    },
    {
      "id": "STR-012",
      "categoria": "Esterni",
      "nome": "Balcone/Terrazzo",
      "descrizione": "Pavimentazione e parapetti",
      "stato_check": "Verifica scarico acque",
      "life_years": 20
    }
  ],
  "maintenance_presets": [
    {
      "id_preset": "P019",
      "titolo": "Verifica impianto riscaldamento centralizzato",
      "trade": "tecnico termico",
      "durata_std_h": 1,
      "costo_manodopera_eur_h": 45,
      "costo_materiali_eur": 10,
      "sku": "MT-HEAT-01",
      "ricorrenza": "annual",
      "priorita": "normal",
      "asset_link": "Masotto Terrace View",
      "note": "sincronizzare con amministratore."
    },
    {
      "id_preset": "P020",
      "titolo": "Inventario e marcatura asset",
      "trade": "manutentore+admin",
      "durata_std_h": 3,
      "costo_manodopera_eur_h": 35,
      "costo_materiali_eur": 25,
      "sku": "MT-ASSET-01",
      "ricorrenza": "annual",
      "priorita": "normal",
      "asset_link": "tutti",
      "note": "collezionare seriali mancanti."
    }
  ],
  "utility_bills": [
    {
      "id": "UTL-0114",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "523003308591",
      "period": "20.04.23 - 31.05.23",
      "period_start": "2023-04-20",
      "period_end": "2023-05-31",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 91,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0115",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "523004295573",
      "period": "01.06.23 - 31.07.23",
      "period_start": "2023-06-01",
      "period_end": "2023-07-31",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 51,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0116",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "523005118766",
      "period": "01.08.23 - 30.09.23",
      "period_start": "2023-08-01",
      "period_end": "2023-09-30",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 50,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0117",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "524500021378",
      "period": "01.10.23 - 30.11.23",
      "period_start": "2023-10-01",
      "period_end": "2023-11-30",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 52,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0118",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "524502450020",
      "period": "01.12.23 - 31.01.24",
      "period_start": "2023-12-01",
      "period_end": "2024-01-31",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 53,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0119",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "524504672493",
      "period": "01.11.23 - 31.03.24",
      "period_start": "2023-11-01",
      "period_end": "2024-03-31",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 85,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0120",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "524507373776",
      "period": "01.04.24 - 31.05.24",
      "period_start": "2024-04-01",
      "period_end": "2024-05-31",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 100,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0121",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "524509946251",
      "period": "01.06.24 - 31.07.24",
      "period_start": "2024-06-01",
      "period_end": "2024-07-31",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 184,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0122",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "524512952632",
      "period": "01.08.24 - 30.09.24",
      "period_start": "2024-08-01",
      "period_end": "2024-09-30",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 141,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0123",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "524516100278",
      "period": "01.10.24 - 30.11.24",
      "period_start": "2024-10-01",
      "period_end": "2024-11-30",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 157,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "drive_2026_recent_masotto.pdf",
      "verification_status": "matched_from_drive_bill_summary"
    },
    {
      "id": "UTL-0005",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "525502348788",
      "period": "Dic 24 - Gen 25",
      "period_start": null,
      "period_end": null,
      "consumption": 452,
      "unit": "kWh",
      "amount_eur": 192,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0001",
      "property_id": "MASOTTO4",
      "utility": "Gas",
      "bill_number": null,
      "period": "Dic 24 - Feb 25",
      "period_start": null,
      "period_end": null,
      "consumption": 4.02,
      "unit": "Smc",
      "amount_eur": 53,
      "pdr": "05260200407342",
      "fornitura": "6045405179",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0006",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "525505320634",
      "period": "Feb 25 - Mar 25",
      "period_start": null,
      "period_end": null,
      "consumption": 130,
      "unit": "kWh",
      "amount_eur": 94,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0007",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "525508306782",
      "period": "Apr 25 - Mag 25",
      "period_start": null,
      "period_end": null,
      "consumption": 136,
      "unit": "kWh",
      "amount_eur": 89,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0002",
      "property_id": "MASOTTO4",
      "utility": "Gas",
      "bill_number": null,
      "period": "Gen 25 - Mag 25",
      "period_start": null,
      "period_end": null,
      "consumption": 8.04,
      "unit": "Smc",
      "amount_eur": 54,
      "pdr": "05260200407342",
      "fornitura": "6045405179",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0008",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "525511399807",
      "period": "Giu 25 - Lug 25",
      "period_start": null,
      "period_end": null,
      "consumption": 501,
      "unit": "kWh",
      "amount_eur": 195,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0003",
      "property_id": "MASOTTO4",
      "utility": "Gas",
      "bill_number": null,
      "period": "Giu 25 - Ago 25",
      "period_start": null,
      "period_end": null,
      "consumption": 22.12,
      "unit": "Smc",
      "amount_eur": 68,
      "pdr": "05260200407342",
      "fornitura": "6045405179",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0009",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "525514381674",
      "period": "Ago 25 - Set 25",
      "period_start": null,
      "period_end": null,
      "consumption": 181,
      "unit": "kWh",
      "amount_eur": 103,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0004",
      "property_id": "MASOTTO4",
      "utility": "Gas",
      "bill_number": null,
      "period": "Set 25 - Nov 25",
      "period_start": null,
      "period_end": null,
      "consumption": 46.25,
      "unit": "Smc",
      "amount_eur": 87,
      "pdr": "05260200407342",
      "fornitura": "6045405179",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0010",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "525517682443",
      "period": "Ott 25 - Nov 25",
      "period_start": null,
      "period_end": null,
      "consumption": 302,
      "unit": "kWh",
      "amount_eur": 137,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0011",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": "526501962046",
      "period": "N/D",
      "period_start": null,
      "period_end": null,
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 165,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "domiciliata",
      "source_file": "bollette_2emme_complete.json",
      "verification_status": null
    },
    {
      "id": "UTL-0049",
      "property_id": "MASOTTO4",
      "utility": "Gas",
      "bill_number": null,
      "period": "Dic 25 - Feb 26",
      "period_start": "2025-12-01",
      "period_end": "2026-02-28",
      "consumption": 0,
      "unit": "Smc",
      "amount_eur": 83,
      "pdr": "05260200407342",
      "fornitura": "6045405179",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "masotto_operating_database_reconciled_2026-06-14",
      "verification_status": "from_reconciled_local_database_not_pdf_in_session"
    },
    {
      "id": "UTL-0048",
      "property_id": "MASOTTO4",
      "utility": "Luce",
      "bill_number": null,
      "period": "Feb 26 - Mar 26",
      "period_start": "2026-02-01",
      "period_end": "2026-03-31",
      "consumption": 0,
      "unit": "kWh",
      "amount_eur": 221,
      "pod": "IT012E00186429",
      "fornitura": "6045433825",
      "category": "Utenze",
      "payer": "Wise / 2M",
      "status": "pagata",
      "source_file": "masotto_operating_database_reconciled_2026-06-14",
      "verification_status": "from_reconciled_local_database_not_pdf_in_session"
    }
  ],
  "maintenance_tickets_v43": [
    {
      "id": "MNT-0019",
      "asset": null,
      "title": "Silicone lavandino",
      "status": "Completato",
      "date": "2025-10-12",
      "costo_lavoro": 40,
      "costo_materiali": 17,
      "totale_eur": 57,
      "source_file": "user_pasted_masotto_maintenance_materials_2026-06-14",
      "note": null
    },
    {
      "id": "MNT-0020",
      "asset": null,
      "title": "Ripristino cassone tapparella",
      "status": "Completato",
      "date": "2025-10-16",
      "costo_lavoro": 40,
      "costo_materiali": 0,
      "totale_eur": 40,
      "source_file": "user_pasted_masotto_maintenance_materials_2026-06-14",
      "note": null
    },
    {
      "id": "MNT-0021",
      "asset": null,
      "title": "Tinteggiatura bagno, cucina e soggiorno",
      "status": "Completato",
      "date": "2025-10-16",
      "costo_lavoro": 150,
      "costo_materiali": 133,
      "totale_eur": 283,
      "source_file": "user_pasted_masotto_maintenance_materials_2026-06-14",
      "note": null
    },
    {
      "id": "MNT-0022",
      "asset": null,
      "title": "Siliconatura cornici finestre sale e tinteggiatura",
      "status": "Completato",
      "date": "2025-10-21",
      "costo_lavoro": 72,
      "costo_materiali": 28,
      "totale_eur": 100,
      "source_file": "user_pasted_masotto_maintenance_materials_2026-06-14",
      "note": "Costo totale intervento corretto da 197.0 EUR a 100 EUR su indicazione utente; materiali mantenuti a 28.0 EUR e manodopera ricalcolata da 169.0 EUR a 72.0 EUR."
    }
  ],
  "revenue_bookings_v43": [
    {
      "id": "REV-0055",
      "property_id": "MASOTTO4",
      "date": "2025-05-25",
      "channel": "diretta",
      "amount_eur": 658.22,
      "description": null,
      "source_label": "Masotto4 Terrace"
    },
    {
      "id": "REV-0057",
      "property_id": "MASOTTO4",
      "date": "2025-08-25",
      "channel": "airbnb",
      "amount_eur": 121.38,
      "description": null,
      "source_label": "Masotto4 Terrace"
    },
    {
      "id": "REV-0060",
      "property_id": "MASOTTO4",
      "date": "2026-01-12",
      "channel": "diretta",
      "amount_eur": 1428,
      "description": null,
      "source_label": "Masotto4 Terrace"
    }
  ],
  "metadata": {
    "database_name": "GestioneMasotto4",
    "online_update_version": "2026-06-15-repo-update",
    "source_repository_snapshot": "01-GestioneMasotto4-main-5-1-.zip",
    "source_canonical_database": "2mdb_current.json V43",
    "note": "Preservato database reale del repo; convertito masotto_db.js in window.MASOTTO_DB e integrati utility_bills, maintenance_tickets_v43, revenue_bookings_v43 e finances V43.",
    "version": "v56_cash_accrual_fix",
    "updated_note": "Rimosse righe ghost bookings airbnb/diretta; apertura 2026 da liquidita disponibile; Jessika split Wise/Riccardo."
  },
  "maintenance_tickets_v47": [
    {
      "id": 2510121,
      "asset": "STR-009",
      "title": "Silicone lavandino",
      "status": "DONE",
      "date": "2025-10-12",
      "costo_lavoro": 40,
      "costo_materiali": 17,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 57,
      "payment_account": "Wise",
      "category": "Manutenzione"
    },
    {
      "id": 2510161,
      "asset": "STR-004",
      "title": "Ripristino cassone tapparella",
      "status": "DONE",
      "date": "2025-10-16",
      "costo_lavoro": 40,
      "costo_materiali": 0,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 40,
      "payment_account": "Wise",
      "category": "Manutenzione"
    },
    {
      "id": 2510122,
      "asset": "STR-001",
      "title": "Tinteggiatura bagno + cucina/soggiorno",
      "status": "DONE",
      "date": "2025-10-12",
      "costo_lavoro": 250,
      "costo_materiali": 133,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 383,
      "payment_account": "Wise",
      "category": "Manutenzione"
    },
    {
      "id": 2510211,
      "asset": "STR-004",
      "title": "Siliconatura cornici finestre sale e tinteggiatura",
      "status": "DONE",
      "date": "2025-10-21",
      "costo_lavoro": 100,
      "costo_materiali": 28,
      "costo_consumabili": 0,
      "costo_attrezzatura": 0,
      "totale_eur": 128,
      "payment_account": "Wise",
      "category": "Manutenzione"
    }
  ],
  "accounting_rules_v47": {
    "booking_rule": "receipt_date_checkin; taxable=stay_plus_cleaning; city_tax_separate; checkout_generates_cleaning_expense_and_cedolare_accrual",
    "cleaning_fee": {
      "nights_lte_14": 45,
      "nights_gt_14": 80
    },
    "cedolare_rate": 0.21,
    "accounts": {
      "until_2025_12_31": "Wise except IMU/TARI",
      "from_2026": {
        "electricity": "Fineco",
        "gas": "Fineco",
        "internet": "Wise",
        "insurance": "Wise",
        "cleaning": "Wise",
        "maintenance": "Wise",
        "ordinary_consumables": "Wise",
        "condominium": "Fineco"
      }
    },
    "monthly_defaults": {
      "internet": {
        "amount_eur": 27.95,
        "account": "Wise",
        "category": "Utenze",
        "description": "internet Fastweb mensile"
      },
      "ordinary_consumables": {
        "amount_eur": 30,
        "account": "Wise",
        "category": "Gestione ordinaria",
        "description": "consumabili gestione ordinaria"
      }
    }
  },
  "accounting_rules": {
    "receipt_date": "check_in",
    "receipt_taxable_rule": "gross_eur / taxable_gross_eur è la base cedolare e comprende le pulizie se cleaning_eur è presente",
    "city_tax_rule": "city_tax_eur sempre separata, fuori imponibile cedolare, partita di giro",
    "year_end_close": "genera tutte le ricevute e il bilancio per anno senza modificare le prenotazioni",
    "cedolare_rate": 0.21,
    "cash_opening_rule": "L anno successivo parte dal liquidita disponibile, non dal saldo banca prima degli accantonamenti.",
    "year_end_rule": "Liquidita disponibile = fondo iniziale + incassi su conto - uscite reali su conto - accantonamenti fiscali aperti.",
    "accrual_rule": "Cedolare accantonata riduce la disponibilità gestionale. Quando viene versata, esce come pagamento tasse e chiude il debito fiscale.",
    "jessika_125904941": "Base cedolare 1320; pulizie incluse 80; city tax 133 separata; entrata Wise 1320; rimborso/giroconto Riccardo 550+550 in uscita."
  }
};
