window.MASOTTO_DB = {
  "property_master": [
    {
      "property_id": "MASOTTO4",
      "name": "2M Apartments - Masotto Terrace View",
      "address": "Via Privata Umberto Masotto 4, 20133 Milano",
      "owner": "Armati Riccardo",
      "purchase_date": "2023-04-17",
      "purchase_price_eur": 230000,
      "pod_luce": "IT012E00186429",
      "fornitura_luce": "6045433825",
      "mandato_sepa_luce": "S9058160964",
      "pdr_gas": "05260200407342",
      "fornitura_gas": "6045405179",
      "mandato_sepa_gas": "S9878640155",
      "cir": "015146-LNI-09408",
      "ape_class": "E",
      "ape_epgl_nren_kwh_m2": 132.76,
      "ape_validity": "2033-11-30",
      "admin": "Giani & Cantarini S.r.l.",
      "admin_email": "giani.cantarini@gmail.com",
      "admin_phone": "02 76111056",
      "insurance_policy": "440373024",
      "insurance_expiry": "2026-05-31",
      "internet_ssid": "FASTWEB-FC918B",
      "internet_annual_cost_eur": 335.40,
      "avg_annual_kwh": 557,
      "avg_annual_smc": 7,
      "notes": "Teleriscaldamento centralizzato. Posizione condominiale: Esercizio 24/25 chiuso (saldo 0,00€). Preventivo 25/26 regolare (SDD attivo). Straordinarie (Amianto/Terrazza) regolarmente pagate. Nessuna morosità."
    }
  ],
  "assets_mobile": [
    { "id": "EQ031", "tipo": "Frigorifero", "marca": "IKEA", "modello": "HUTTRA", "sn": "IK-FR-8890", "acquisto": "2023-10-02", "prezzo_eur": 409.0, "garanzia": "attiva (2028)", "assistenza": "IKEA Chat/Store" },
    { "id": "EQ032", "tipo": "Lavastoviglie", "marca": "IKEA", "modello": "MEDELSTOR", "sn": "IK-DW-221", "acquisto": "2023-10-02", "prezzo_eur": 419.0, "garanzia": "attiva (2028)", "assistenza": "IKEA Chat/Store" },
    { "id": "EQ033", "tipo": "Piano Cottura", "marca": "IKEA", "modello": "VILSTA (Induzione)", "sn": "IK-IND-55", "acquisto": "2023-10-02", "prezzo_eur": 239.0, "garanzia": "attiva (2028)", "assistenza": "IKEA Chat/Store" },
    { "id": "EQ034", "tipo": "Cappa", "marca": "IKEA", "modello": "UTDRAG", "sn": "-", "acquisto": "2023-10-02", "prezzo_eur": 149.0, "garanzia": "scaduta (2025)", "assistenza": "IKEA Chat/Store" },
    { "id": "EQ041", "tipo": "Lavasciuga", "marca": "MIELE", "modello": "Softtronic WT 2670", "sn": "86308219", "acquisto": "2019-09-01", "prezzo_eur": 459.0, "garanzia": "scaduta (2021)", "assistenza": "800-845677" },
    { "id": "EQ037", "tipo": "TV 43", "marca": "HISENSE", "modello": "43E63KT", "sn": "36FG5G23113PITADPL53889", "acquisto": "2023-11-06", "prezzo_eur": 299.0, "garanzia": "attiva (2027)", "assistenza": "800-321999" },
    { "id": "EQ093", "tipo": "Macchina Caffè", "marca": "LAVAZZA", "modello": "Jolie Evo", "sn": "YWU9AJPKFPKER9WC", "acquisto": "2024-11-14", "prezzo_eur": 94.9, "garanzia": "attiva (2026)", "assistenza": "Servizio A Modo Mio" },
    { "id": "EQ044", "tipo": "Aspirapolvere 2in1", "marca": "BLACK+DECKER", "modello": "BXVMS600E", "sn": "44491HK", "acquisto": "2026-01-04", "prezzo_eur": 49.0, "garanzia": "attiva (2028)", "assistenza": "Centro Ass. Milano" },
    { "id": "EQ036", "tipo": "Condizionatore", "marca": "CANDY", "modello": "CY-09TAOUT", "sn": "AABL7GEO00ON1P5R0599", "acquisto": "2023-10-02", "prezzo_eur": 0.0, "garanzia": "scaduta (2025)", "assistenza": "02-445566" },
    { "id": "EQ099", "tipo": "Materasso", "marca": "IKEA", "modello": "VAGSTRANDA", "sn": "-", "acquisto": "2023-10-02", "prezzo_eur": 399.0, "garanzia": "attiva (2033)", "assistenza": "IKEA Chat/Store" },
    { "id": "EQ100", "tipo": "Topper", "marca": "IKEA", "modello": "TUSTNA", "sn": "-", "acquisto": "2023-10-02", "prezzo_eur": 150.0, "garanzia": "scaduta (2025)", "assistenza": "IKEA Chat/Store" },
    { "id": "EQ101", "tipo": "Asse/Stiro", "marca": "STANDARD", "modello": "Stiro Kit", "sn": "-", "acquisto": "2026-02-09", "prezzo_eur": 39.0, "garanzia": "n/a", "assistenza": "-" },
    { "id": "EQ102", "tipo": "Frullatore", "marca": "STANDARD", "modello": "Blender", "sn": "-", "acquisto": "2026-02-09", "prezzo_eur": 59.0, "garanzia": "n/a", "assistenza": "-" },
    { "id": "EQ103", "tipo": "Grucce", "marca": "GENERICO", "modello": "Set 10", "sn": "-", "acquisto": "2026-02-09", "prezzo_eur": 12.0, "garanzia": "n/a", "assistenza": "-" }
  ],
  "structural_assets": [
    { "id": "STR-001", "categoria": "Involucro", "nome": "Pareti Interne", "descrizione": "Intonaci e tinteggiatura smalto", "stato_check": "Ripristino Ott 2025", "life_years": 5 },
    { "id": "STR-002", "categoria": "Involucro", "nome": "Soffitti", "descrizione": "Finitura muraria e pitturazioni", "stato_check": "Monitoraggio crepe", "life_years": 8 },
    { "id": "STR-003", "categoria": "Involucro", "nome": "Pavimenti", "descrizione": "Gres Porcellanato e zoccolini", "stato_check": "Verifica fughe", "life_years": 15 },
    { "id": "STR-004", "categoria": "Infissi", "nome": "Infissi Esterni", "descrizione": "PVC Doppio Vetro / Guarnizioni", "stato_check": "Check isolamento", "life_years": 30 },
    { "id": "STR-005", "categoria": "Infissi", "nome": "Porte Interne", "descrizione": "Ante, telai e serrature", "stato_check": "Lubrificazione cerniere", "life_years": 20 },
    { "id": "STR-006", "categoria": "Sicurezza", "nome": "Porta Ingresso", "descrizione": "Blindata Dierre / Cilindro Euro", "stato_check": "Check spioncino", "life_years": 40 },
    { "id": "STR-007", "categoria": "Impianti", "nome": "Imp. Elettrico", "descrizione": "Quadro RCD, prese e frutti", "stato_check": "Certificato Ott 2023", "life_years": 20 },
    { "id": "STR-008", "categoria": "Impianti", "nome": "Imp. Idraulico", "descrizione": "Tubazioni e attacchi cucina", "stato_check": "Audit scarichi OK", "life_years": 25 },
    { "id": "STR-009", "categoria": "Bagno", "nome": "Comp. Fissi", "descrizione": "WC, lavabo e piatto doccia", "stato_check": "Verifica miscelatori", "life_years": 15 },
    { "id": "STR-010", "categoria": "Sigilli", "nome": "Siliconature", "descrizione": "Sigillature bagno e cucina", "stato_check": "RIUSO: Silicone disp.", "life_years": 2 },
    { "id": "STR-011", "categoria": "Clima", "nome": "Riscaldamento", "descrizione": "Centralizzato Techem / Valvole", "stato_check": "Contabilizzato Feb 26", "life_years": 20 },
    { "id": "STR-012", "categoria": "Esterni", "nome": "Balcone/Terrazzo", "descrizione": "Pavimentazione e parapetti", "stato_check": "Verifica scarico acque", "life_years": 20 }
  ],
  "finances": [
    { "id": 2403051, "date": "2024-03-05", "description": "A2A Luce", "category": "Utenze", "amount_eur": 53.00, "status": "paid" },
    { "id": 2403191, "date": "2024-03-19", "description": "A2A Gas", "category": "Utenze", "amount_eur": 45.00, "status": "paid" },
    { "id": 2404221, "date": "2024-04-22", "description": "A2A Luce", "category": "Utenze", "amount_eur": 85.00, "status": "paid" },
    { "id": 2406191, "date": "2024-06-19", "description": "A2A Luce", "category": "Utenze", "amount_eur": 100.00, "status": "paid" },
    { "id": 2409171, "date": "2024-09-17", "description": "A2A Gas", "category": "Utenze", "amount_eur": 61.00, "status": "paid" },
    { "id": 2410171, "date": "2024-10-17", "description": "A2A Luce", "category": "Utenze", "amount_eur": 141.00, "status": "paid" },
    { "id": 2412161, "date": "2024-12-16", "description": "A2A Gas", "category": "Utenze", "amount_eur": 67.00, "status": "paid" },
    { "id": 2412191, "date": "2024-12-19", "description": "A2A Luce", "category": "Utenze", "amount_eur": 157.00, "status": "paid" },
    { "id": 2503101, "date": "2025-03-10", "description": "A2A Luce (Dic 24-Gen 25)", "category": "Utenze", "amount_eur": 192.00, "status": "paid" },
    { "id": 2504071, "date": "2025-04-07", "description": "A2A Gas (Dic 24-Feb 25)", "category": "Utenze", "amount_eur": 53.00, "status": "paid" },
    { "id": 2505051, "date": "2025-05-05", "description": "A2A Luce (Feb-Mar 25)", "category": "Utenze", "amount_eur": 94.00, "status": "paid" },
    { "id": 2507071, "date": "2025-07-07", "description": "A2A Luce (Apr-Mag 25)", "category": "Utenze", "amount_eur": 89.00, "status": "paid" },
    { "id": 2507072, "date": "2025-07-07", "description": "A2A Gas (Gen-Mag 25)", "category": "Utenze", "amount_eur": 54.00, "status": "paid" },
    { "id": 2509031, "date": "2025-09-03", "description": "A2A Luce (Giu-Lug 25)", "category": "Utenze", "amount_eur": 195.00, "status": "paid" },
    { "id": 2510021, "date": "2025-10-02", "description": "A2A Gas (Giu-Ago 25)", "category": "Utenze", "amount_eur": 68.00, "status": "paid" },
    { "id": 2511031, "date": "2025-11-03", "description": "A2A Luce (Ago-Set 25)", "category": "Utenze", "amount_eur": 103.00, "status": "paid" },
    { "id": 2601051, "date": "2026-01-05", "description": "A2A Luce (Ott-Nov 25)", "category": "Utenze", "amount_eur": 137.00, "status": "paid" },
    { "id": 2601052, "date": "2026-01-05", "description": "A2A Gas (Set-Nov 25)", "category": "Utenze", "amount_eur": 87.00, "status": "paid" },
    { "id": 2603041, "date": "2026-03-04", "description": "A2A Luce (Dic 25-Gen 26)", "category": "Utenze", "amount_eur": 165.00, "status": "paid" },
    { "id": 2501012, "date": "2025-01-01", "description": "Internet Fastweb Quota Annua", "category": "Utenze", "amount_eur": 335.40, "status": "paid" },
    { "id": 2312051, "date": "2023-12-05", "description": "Condominio: Ripartitori di Calore", "category": "Straordinaria", "amount_eur": 125.52, "status": "paid" },
    { "id": 2406301, "date": "2024-06-30", "description": "Condominio: Rata fp nr. 1 (24/25)", "category": "Ordinaria", "amount_eur": 256.20, "status": "paid" },
    { "id": 2411151, "date": "2024-11-15", "description": "Condominio: f.p. N. 2 (24/25)", "category": "Ordinaria", "amount_eur": 256.20, "status": "paid" },
    { "id": 2502151, "date": "2025-02-15", "description": "Condominio: Rata n. 3 e saldo (24/25)", "category": "Ordinaria", "amount_eur": 522.16, "status": "paid" },
    { "id": 2504011, "date": "2025-04-01", "description": "Condominio: Rata n. 4 (24/25)", "category": "Ordinaria", "amount_eur": 395.77, "status": "paid" },
    { "id": 2503201, "date": "2025-03-20", "description": "Condominio: Rimozione MCA (Amianto) R1", "category": "Straordinaria", "amount_eur": 285.33, "status": "paid" },
    { "id": 2506151, "date": "2025-06-15", "description": "Condominio: Rimozione MCA (Amianto) R2", "category": "Straordinaria", "amount_eur": 285.33, "status": "paid" },
    { "id": 2506152, "date": "2025-06-15", "description": "Condominio: Ordinaria Rata 1 (25/26)", "category": "Ordinaria", "amount_eur": 305.00, "status": "paid" },
    { "id": 2509011, "date": "2025-09-01", "description": "Condominio: Ordinaria Rata 2 (25/26)", "category": "Ordinaria", "amount_eur": 305.00, "status": "paid" },
    { "id": 2512151, "date": "2025-12-15", "description": "Condominio: Terrazza R3 + Amianto R1", "category": "Straordinaria", "amount_eur": 598.67, "status": "paid" },
    { "id": 2602151, "date": "2026-02-15", "description": "Condominio: Terrazza Rata 4", "category": "Straordinaria", "amount_eur": 318.20, "status": "paid" },
    { "id": 2501011, "date": "2025-01-31", "description": "Canone RAI 2025", "category": "Tasse", "amount_eur": 203.70, "status": "paid" },
    { "id": 2506161, "date": "2025-06-16", "description": "IMU Acconto 2025", "category": "Tasse", "amount_eur": 334.00, "status": "paid" },
    { "id": 2512051, "date": "2025-12-05", "description": "TARI 2025", "category": "Tasse", "amount_eur": 139.00, "status": "paid" },
    { "id": 2512101, "date": "2025-12-10", "description": "Assicurazione 2025", "category": "Fisse", "amount_eur": 195.00, "status": "paid" },
    { "id": 2512161, "date": "2025-12-16", "description": "IMU Saldo 2025", "category": "Tasse", "amount_eur": 334.00, "status": "paid" },
    { "id": 2510121, "date": "2025-10-12", "description": "Manutenzione: Silicone lavandino", "category": "Straordinaria", "amount_eur": 57.00, "status": "paid" },
    { "id": 2510122, "date": "2025-10-12", "description": "Manutenzione: Pitturare cucina e soggiorno", "category": "Straordinaria", "amount_eur": 276.00, "status": "paid" },
    { "id": 2510161, "date": "2025-10-16", "description": "Manutenzione: Ripristino cassone tapparella", "category": "Straordinaria", "amount_eur": 40.00, "status": "paid" },
    { "id": 2510162, "date": "2025-10-16", "description": "Manutenzione: Tinteggiatura bagno", "category": "Straordinaria", "amount_eur": 187.00, "status": "paid" },
    { "id": 2510211, "date": "2025-10-21", "description": "Manutenzione: Siliconatura cornici finestre", "category": "Straordinaria", "amount_eur": 197.00, "status": "paid" },
    { "id": 2601081, "date": "2026-01-08", "description": "Asset: Aspirapolvere BLACK+DECKER", "category": "Asset", "amount_eur": 49.00, "status": "paid" },
    { "id": 2602091, "date": "2026-02-09", "description": "Asset: Asse Vileda", "category": "Asset", "amount_eur": 63.49, "status": "paid" },
    { "id": 2602101, "date": "2026-02-10", "description": "Asset: Set Asciugamani", "category": "Asset", "amount_eur": 23.15, "status": "paid" },
    { "id": 2602102, "date": "2026-02-10", "description": "Asset: Frullatore + Grucce", "category": "Asset", "amount_eur": 44.74, "status": "paid" },
    { "id": 2511001, "date": "2025-11-01", "description": "Fee Gestione 2M (Novembre-Dicembre)", "category": "Fee Gestione", "amount_eur": 1000.00, "status": "paid", "type": "expense" }
  ],
  "bookings": [
    { "id": 108603411, "guest": "Gabriela Stempka", "check_in": "2025-08-25", "nights": 2, "pax": 2, "source": "Airbnb", "gross_eur": 143.00, "commission_eur": 21.42, "city_tax_eur": 25.20 },
    { "id": 108845191, "guest": "Flavio Nakakura", "check_in": "2025-08-27", "nights": 7, "pax": 1, "source": "Diretta", "gross_eur": 452.00, "commission_eur": 0, "city_tax_eur": 44.10 },
    { "id": 107696481, "guest": "Christie Swainston", "check_in": "2025-09-04", "nights": 3, "pax": 1, "source": "Airbnb", "gross_eur": 441.00, "commission_eur": 66.15, "city_tax_eur": 18.90 },
    { "id": 109488256, "guest": "Flavio Nakakura", "check_in": "2025-09-07", "nights": 22, "pax": 1, "source": "Diretta", "gross_eur": 1267.00, "commission_eur": 0, "city_tax_eur": 88.20 },
    { "id": 112211526, "guest": "Edwin Agallanes", "check_in": "2025-09-30", "nights": 13, "pax": 1, "source": "Diretta", "gross_eur": 850.00, "commission_eur": 0, "city_tax_eur": 81.30 },
    { "id": 113874751, "guest": "Maja Janevska", "check_in": "2025-10-16", "nights": 10, "pax": 1, "source": "Diretta", "gross_eur": 826.00, "commission_eur": 0, "city_tax_eur": 63.00 },
    { "id": 115489991, "guest": "Irilla Santana", "check_in": "2025-10-26", "nights": 15, "pax": 1, "source": "Diretta", "gross_eur": 1000.00, "commission_eur": 0, "city_tax_eur": 88.20 },
    { "id": 115489992, "guest": "Irilla Santana", "check_in": "2025-11-12", "nights": 15, "pax": 1, "source": "Diretta", "gross_eur": 1000.00, "commission_eur": 0, "city_tax_eur": 88.20 },
    { "id": 119791626, "guest": "Sara Dario", "check_in": "2025-12-04", "nights": 17, "pax": 1, "source": "Diretta", "gross_eur": 1214.29, "commission_eur": 0, "city_tax_eur": 88.20 },
    { "id": 123607671, "guest": "Sara Dario", "check_in": "2026-01-12", "nights": 14, "pax": 1, "source": "Diretta", "gross_eur": 1000.00, "commission_eur": 0, "city_tax_eur": 88.20 },
    { "id": 125904941, "guest": "Jessika de Miranda", "check_in": "2026-02-09", "nights": 30, "pax": 1, "source": "Diretta", "gross_eur": 1598.00, "commission_eur": 0, "city_tax_eur": 88.20 }
  ],
  "tickets": [
    { 
      "id": 2510121, "asset": "STR-009", "title": "Silicone lavandino", "status": "DONE", "date": "2025-10-12", "priority": "Alta", 
      "costo_lavoro": 40.00, "costo_materiali": 17.00, "durata_h": 1.0, "assegnato": "Idraulico/Manutentore", 
      "consumables": "Silicone sanitario (2 cartucce); Alcool denaturato; Nastro carta", 
      "reusables": "Raschietto", 
      "inventory_processed": true 
    },
    { 
      "id": 2510122, "asset": "STR-001", "title": "Pitturare cucina e soggiorno", "status": "DONE", "date": "2025-10-12", "priority": "Media", 
      "costo_lavoro": 180.00, "costo_materiali": 96.00, "durata_h": 4.0, "assegnato": "Imbianchino", 
      "consumables": "Vernice lavabile 3 L (2 mani); Primer 1 L; Nastro carta; Fogli protezione", 
      "reusables": "Set pennelli, Rullo professionale", 
      "inventory_processed": true 
    },
    { 
      "id": 2510161, "asset": "STR-004", "title": "Ripristino cassone tapparella", "status": "DONE", "date": "2025-10-16", "priority": "Media", 
      "costo_lavoro": 40.00, "costo_materiali": 0.00, "durata_h": 1.0, "assegnato": "Manutentore", 
      "consumables": "", 
      "reusables": "", 
      "inventory_processed": true 
    },
    { 
      "id": 2510162, "asset": "STR-001", "title": "Tinteggiatura bagno", "status": "DONE", "date": "2025-10-16", "priority": "Media", 
      "costo_lavoro": 150.00, "costo_materiali": 37.00, "durata_h": 1.0, "assegnato": "Manutentore/Imbianchino", 
      "consumables": "Vernice bagno idrorepellente 1 L; Nastro carta", 
      "reusables": "Set pennelli, Rullo piccolo", 
      "inventory_processed": true 
    },
    { 
      "id": 2510211, "asset": "STR-004", "title": "Siliconatura cornici finestre e tinteggiatura", "status": "DONE", "date": "2025-10-21", "priority": "Media", 
      "costo_lavoro": 169.00, "costo_materiali": 28.00, "durata_h": 1.0, "assegnato": "Manutentore/Imbianchino", 
      "consumables": "Silicone acrilico 2 cartucce; Vernice 0.5 L; Nastro carta", 
      "reusables": "Set pennelli", 
      "inventory_processed": true 
    }
  ],
  "reusable_inventory": [
    { "id": "TOOL-01", "nome": "Raschietto", "categoria": "Attrezzi Manuali", "data_acquisizione": "2025-10-12", "valore_stimato_eur": 5.00, "usi_rimanenti": 4 },
    { "id": "TOOL-02", "nome": "Set pennelli", "categoria": "Pittura", "data_acquisizione": "2025-10-12", "valore_stimato_eur": 12.00, "usi_rimanenti": 2 },
    { "id": "TOOL-03", "nome": "Rullo professionale", "categoria": "Pittura", "data_acquisizione": "2025-10-12", "valore_stimato_eur": 15.00, "usi_rimanenti": 3 },
    { "id": "TOOL-04", "nome": "Rullo piccolo", "categoria": "Pittura", "data_acquisizione": "2025-10-16", "valore_stimato_eur": 6.00, "usi_rimanenti": 2 }
  ],
  "maintenance_presets": [
     { "id": "MNT-EQ041-001", "asset_id": "EQ041", "title": "Check annuale + pulizia filtro", "trade": "tecnico elettrodomestici", "durata_h": 1.50, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 60.00, "costo_materiali_eur": 5.00, "materiali": ["Filtro sostitutivo (se necessario)", "detergente non aggressivo"], "ricorrenza": "annual", "priorita": "normal", "estimated_total_eur": 65.00, "note": "Pulizia filtro, controllo guarnizioni, test centrifuga" },
     { "id": "MNT-EQ041-002", "asset_id": "EQ041", "title": "Intervento rapido (centrifuga / blocco)", "trade": "tecnico elettrodomestici", "durata_h": 2.00, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 80.00, "costo_materiali_eur": 50.00, "materiali": ["guarnizioni", "clip di fissaggio", "piccoli ricambi elettrici"], "ricorrenza": "on-demand", "priorita": "high", "estimated_total_eur": 130.00, "note": "Intervento diagnostico + riparazione rapida, foto guasto obbligatorie" },
     { "id": "MNT-EQ041-003", "asset_id": "EQ041", "title": "Sostituzione componenti maggiori (cinghia/cuscinetti)", "trade": "tecnico elettrodomestici", "durata_h": 3.00, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 120.00, "costo_materiali_eur": 120.00, "materiali": ["cinghia", "cuscinetti", "lubrificante specifico"], "ricorrenza": "one-off", "priorita": "high", "estimated_total_eur": 240.00, "note": "Preventivo prima dell'acquisto pezzi; usare garanzia se applicabile" },
     { "id": "MNT-EQ032-001", "asset_id": "EQ032", "title": "Check cicli + pulizia filtro", "trade": "tecnico elettrodomestici", "durata_h": 1.00, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 40.00, "costo_materiali_eur": 10.00, "materiali": ["filtro sostitutivo", "detergente per filtri"], "ricorrenza": "annual", "priorita": "normal", "estimated_total_eur": 50.00, "note": "Verifica pompe, guarnizioni e perdite" },
     { "id": "MNT-EQ032-002", "asset_id": "EQ032", "title": "Sostituzione pompa/valvola", "trade": "tecnico elettrodomestici", "durata_h": 2.50, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 100.00, "costo_materiali_eur": 80.00, "materiali": ["pompa di carico", "valvola ingresso acqua", "guarnizioni"], "ricorrenza": "one-off", "priorita": "high", "estimated_total_eur": 180.00, "note": "Richiede test finale su ciclo completo" },
     { "id": "MNT-EQ033-001", "asset_id": "EQ033", "title": "Verifica sensori + rimozione incrostazioni", "trade": "tecnico elettrodomestici", "durata_h": 1.00, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 40.00, "costo_materiali_eur": 5.00, "materiali": ["spray pulente vetroceramica", "panni microfibra"], "ricorrenza": "annual", "priorita": "normal", "estimated_total_eur": 45.00, "note": "Controllo sensori touch e connessioni elettriche" },
     { "id": "MNT-EQ033-002", "asset_id": "EQ033", "title": "Sostituzione sensore / riparazione elettronica", "trade": "tecnico elettrodomestici", "durata_h": 2.00, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 80.00, "costo_materiali_eur": 90.00, "materiali": ["sensore touch", "connettori", "paste termiche"], "ricorrenza": "on-demand", "priorita": "high", "estimated_total_eur": 170.00, "note": "Verificare disponibilità ricambio prima dell'intervento" },
     { "id": "MNT-EQ031-001", "asset_id": "EQ031", "title": "Pulizia condensatore + check termostato", "trade": "tecnico frigorista", "durata_h": 1.00, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 40.00, "costo_materiali_eur": 5.00, "materiali": ["spazzola condensatore", "detersivo sgrassante"], "ricorrenza": "annual", "priorita": "normal", "estimated_total_eur": 45.00, "note": "Migliora efficienza e consumo energetico" },
     { "id": "MNT-EQ031-002", "asset_id": "EQ031", "title": "Sostituzione compressore (major)", "trade": "tecnico frigorista", "durata_h": 4.00, "costo_manodopera_eur_h": 60.00, "costo_manodopera_eur": 240.00, "costo_materiali_eur": 350.00, "materiali": ["compressore compatibile", "kit guarnizioni", "olio frigorifero"], "ricorrenza": "one-off", "priorita": "urgent", "estimated_total_eur": 590.00, "note": "Preventivo obbligatorio; intervento specialistico" },
     { "id": "MNT-EQ036-001", "asset_id": "EQ036", "title": "Pre-estate: pulizia filtri + check gas", "trade": "tecnico HVAC", "durata_h": 1.50, "costo_manodopera_eur_h": 50.00, "costo_manodopera_eur": 75.00, "costo_materiali_eur": 30.00, "materiali": ["filtri sostitutivi", "gas R-32 (se necessario)"], "ricorrenza": "biannual", "priorita": "normal", "estimated_total_eur": 105.00, "note": "Controllare perdite; ricarica gas solo se necessaria e documentata" },
     { "id": "MNT-EQ036-002", "asset_id": "EQ036", "title": "Revisione compressore / elettronica", "trade": "tecnico HVAC", "durata_h": 3.00, "costo_manodopera_eur_h": 50.00, "costo_manodopera_eur": 150.00, "costo_materiali_eur": 200.00, "materiali": ["compressore/supporti", "scheda elettronica", "filtro essiccatore"], "ricorrenza": "on-demand", "priorita": "high", "estimated_total_eur": 350.00, "note": "Intervento specialistico; richiede permessi per manipolazione gas" },
     { "id": "MNT-EQ037-001", "asset_id": "EQ037", "title": "Pulizia + controllo telecomando e connessioni", "trade": "tecnico elettronica", "durata_h": 0.50, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 20.00, "costo_materiali_eur": 0.00, "materiali": ["panni microfibra"], "ricorrenza": "annual", "priorita": "normal", "estimated_total_eur": 20.00, "note": "Verificare aggiornamenti firmware se accessibile" },
     { "id": "MNT-EQ037-002", "asset_id": "EQ037", "title": "Riparazione scheda madre / panel", "trade": "tecnico elettronica", "durata_h": 2.50, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 100.00, "costo_materiali_eur": 120.00, "materiali": ["scheda madre/panel sostitutivo", "connettori"], "ricorrenza": "on-demand", "priorita": "high", "estimated_total_eur": 220.00, "note": "Spesso più conveniente la sostituzione completa; valutare costi" },
     { "id": "MNT-EQ093-001", "asset_id": "EQ093", "title": "Decalcificazione + check funzionale", "trade": "tecnico caffetteria", "durata_h": 0.75, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 30.00, "costo_materiali_eur": 5.00, "materiali": ["decalcificante", "kit guarnizioni (se necessario)"], "ricorrenza": "quarterly", "priorita": "normal", "estimated_total_eur": 35.00, "note": "Mantiene durata garanzia e qualità erogazione" },
     { "id": "MNT-EQ093-002", "asset_id": "EQ093", "title": "Sostituzione pompa / guarnizioni", "trade": "tecnico caffetteria", "durata_h": 1.50, "costo_manodopera_eur_h": 40.00, "costo_manodopera_eur": 60.00, "costo_materiali_eur": 30.00, "materiali": ["pompa", "guarnizioni", "filtro"], "ricorrenza": "on-demand", "priorita": "high", "estimated_total_eur": 90.00, "note": "Foto guasto e serie macchina richieste" },
     { "id": "MNT-EQ044-001", "asset_id": "EQ044", "title": "Pulizia filtri + controllo batteria", "trade": "manutentore", "durata_h": 0.50, "costo_manodopera_eur_h": 30.00, "costo_manodopera_eur": 15.00, "costo_materiali_eur": 0.00, "materiali": ["panni", "aria compressa (opzionale)"], "ricorrenza": "quarterly", "priorita": "normal", "estimated_total_eur": 15.00, "note": "Sostituire filtri se usurati" },
     { "id": "MNT-EQ044-002", "asset_id": "EQ044", "title": "Sostituzione batteria / intervento riparazione", "trade": "manutentore", "durata_h": 1.50, "costo_manodopera_eur_h": 30.00, "costo_manodopera_eur": 45.00, "costo_materiali_eur": 50.00, "materiali": ["batteria compatibile", "viti di fissaggio"], "ricorrenza": "on-demand", "priorita": "normal", "estimated_total_eur": 95.00, "note": "Registrare seriale e foto prima dell'intervento" },
     { "id": "MNT-EQ099-001", "asset_id": "EQ099", "title": "Controllo integrità + igienizzazione", "trade": "housekeeping", "durata_h": 1.00, "costo_manodopera_eur_h": 30.00, "costo_manodopera_eur": 30.00, "costo_materiali_eur": 10.00, "materiali": ["disinfettante tessuti", "copertura igienica usa e getta"], "ricorrenza": "annual", "priorita": "normal", "estimated_total_eur": 40.00, "note": "Annotare usura su scheda asset; sostituire topper se >30% usura" },
     { "id": "MNT-EQ101-001", "asset_id": "EQ101", "title": "Controllo funzione e stabilità (asse da stiro)", "trade": "manutentore", "durata_h": 0.25, "costo_manodopera_eur_h": 25.00, "costo_manodopera_eur": 6.25, "costo_materiali_eur": 0.00, "materiali": [], "ricorrenza": "annual", "priorita": "low", "estimated_total_eur": 6.25, "note": "Controllare gambe e blocchi" },
     { "id": "MNT-EQ102-001", "asset_id": "EQ102", "title": "Pulizia e test funzionamento (frullatore)", "trade": "manutentore", "durata_h": 0.25, "costo_manodopera_eur_h": 25.00, "costo_manodopera_eur": 6.25, "costo_materiali_eur": 0.00, "materiali": [], "ricorrenza": "annual", "priorita": "low", "estimated_total_eur": 6.25, "note": "Controllare lame e guarnizioni" },
     { "id": "MNT-EQ103-001", "asset_id": "EQ103", "title": "Inventario e sostituzione grucce danneggiate", "trade": "housekeeping", "durata_h": 0.25, "costo_manodopera_eur_h": 25.00, "costo_manodopera_eur": 6.25, "costo_materiali_eur": 0.00, "materiali": ["set grucce di ricambio"], "ricorrenza": "monthly", "priorita": "low", "estimated_total_eur": 6.25, "note": "Tenere minimo 2 set di scorta in magazzino" },
     { "id": "MNT-STR-007-001", "asset_id": "STR-007", "title": "Verifica annuale impianto elettrico (certificato)", "trade": "elettricista", "durata_h": 2.00, "costo_manodopera_eur_h": 50.00, "costo_manodopera_eur": 100.00, "costo_materiali_eur": 20.00, "materiali": ["materiale di consumo elettrico", "connessioni"], "ricorrenza": "annual", "priorita": "high", "estimated_total_eur": 120.00, "note": "Verifica dispersioni, RCD, etichettatura quadro" },
     { "id": "MNT-STR-011-001", "asset_id": "STR-011", "title": "Verifica contabilizzatori / valvole (risc.)", "trade": "tecnico termico", "durata_h": 1.50, "costo_manodopera_eur_h": 45.00, "costo_manodopera_eur": 67.50, "costo_materiali_eur": 15.00, "materiali": ["guarnizioni valvole", "sigillanti"], "ricorrenza": "annual", "priorita": "high", "estimated_total_eur": 82.50, "note": "Sincronizzare attività con amministratore di condominio" },
     { "id": "MNT-STR-012-001", "asset_id": "STR-012", "title": "Ispezione balcone/terrazzo + ripristino giunti", "trade": "muratore / falegname", "durata_h": 2.50, "costo_manodopera_eur_h": 35.00, "costo_manodopera_eur": 87.50, "costo_materiali_eur": 120.00, "materiali": ["malta impermeabilizzante", "sigillanti", "fughe"], "ricorrenza": "biennial", "priorita": "normal", "estimated_total_eur": 207.50, "note": "Controllare scarichi e parapetti; foto pre/post lavoro" },
     { "id": "MNT-STR-001-001", "asset_id": "STR-001", "title": "Ritocco pittura pareti (intervento di ripristino)", "trade": "pittore", "durata_h": 3.00, "costo_manodopera_eur_h": 35.00, "costo_manodopera_eur": 105.00, "costo_materiali_eur": 50.00, "materiali": ["vernice brand", "stucco", "pennelli/rotoli"], "ricorrenza": "biennial", "priorita": "normal", "estimated_total_eur": 155.00, "note": "Usare palette brand 2M; documentare con foto" }
  ],
  "insurance": [],
  "utilities": [],
  "contacts": []
};